# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=5000, null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('category_mdf', "can modify Article'category"), ('title_mdf', "Can modify Article' title"), ('context_mdf', "Can modify Article' context")),
            },
        ),
        migrations.CreateModel(
            name='Article_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
            ],
            options={
                'permissions': (('name_mdf', 'Can modify the Author_name'), ('Email_mdf', 'Can modify the Author_Email '), ('tel_mdf', 'Can modify author_tel')),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createBy', models.CharField(max_length=128, null=True)),
                ('updatetime', models.DateTimeField(null=True)),
                ('updateBy', models.CharField(max_length=128, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
            ],
            options={
                'permissions': (('category_mdf', 'Can modify the name and remark about the category'),),
            },
        ),
        migrations.CreateModel(
            name='GW_pre_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintNum', models.CharField(max_length=20)),
                ('PrintName', models.CharField(max_length=200)),
                ('sidetype', models.IntegerField(choices=[(1, '4k'), (2, '8K'), (3, '16K'), (4, '32K')], default=1)),
                ('SubCode', models.CharField(default='A', max_length=10)),
                ('WorkType', models.CharField(choices=[('SMY', ' 数码样'), ('LZ', '蓝纸'), ('CTP', 'CTP'), ('CTF', 'CTF'), ('GB', '改版'), ('SBL', '算倍率'), ('COPTDOT', 'COPYDOT'), ('KP', '刻盘')], max_length=50)),
                ('WorkData', models.DateField(null=True)),
                ('FinishQty', models.IntegerField(default=0)),
                ('K_val', models.FloatField(default=0.0)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createBy', models.CharField(max_length=20, null=True)),
                ('updatetime', models.DateTimeField(null=True)),
                ('updateBy', models.CharField(max_length=20, null=True)),
                ('posttime', models.DateTimeField(null=True)),
                ('postBy', models.CharField(max_length=20, null=True)),
                ('CheckTime', models.DateTimeField(null=True)),
                ('CheckBy', models.CharField(max_length=20, null=True)),
                ('staticcode', models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], default='DRAFT', max_length=20)),
                ('menber', models.TextField(max_length=200)),
                ('remark', models.TextField(max_length=300, null=True)),
            ],
            options={
                'permissions': (('gw_draft_post', '工务初稿到过帐'), ('gw_post_checked', '工务已过帐记录审批'), ('gw_post_draft', '工务已过帐发还到初稿'), ('gw_checked_draft', '工务已批核发还到初稿'), ('gw_delete', '工务初稿删除'), ('gw_post_delete', '工务已过帐删除'), ('gw_checked_delete', '工务已批核删除'), ('gw_delete_draft', '工务已经删除到初稿')),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tango_app.Article_Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='Tango_app.Category'),
        ),
    ]
