# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_author',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='article_author',
            name='article',
            field=models.ManyToManyField(to='Tango_app.Article'),
        ),
        migrations.AddField(
            model_name='article_author',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='Tango_app.Category'),
        ),
    ]
