# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0002_auto_20171103_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatetime',
            field=models.DateTimeField(default=None),
        ),
    ]
