# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0003_auto_20171128_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default='2017-11-01'),
        ),
    ]
