# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0004_auto_20171104_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateBy',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
