# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0005_auto_20171104_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_author',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tango_app.Article_Author'),
        ),
    ]
