# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0005_auto_20171129_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 5)),
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
