# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0006_auto_20171205_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRO_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintNum', models.CharField(max_length=20)),
                ('PrintName', models.CharField(max_length=200)),
                ('SubCode', models.CharField(default='A', max_length=10)),
                ('WorkType', models.CharField(choices=[('SJ', '收集'), ('ZZJC', '制作检查'), ('XT', '修图'), ('TD', '褪底'), ('ZZ', '制作'), ('GB', '改版'), ('FP', '发排'), ('PDF_FP', 'PDF发排'), ('PDF_TWJ', 'PDF替文件'), ('PDF_GB', 'PDF改版'), ('CSMY', '出数码样'), ('CLZ', '出蓝纸'), ('KGP', '克光盘')], max_length=20)),
                ('WorkData', models.DateField(null=True)),
                ('WorkTimeType', models.CharField(choices=[('A', '白班'), ('B', '夜班')], default='A', max_length=10)),
                ('FinishQty', models.IntegerField(default=0)),
                ('K_val', models.FloatField(default=0.0)),
                ('LeaderCode', models.CharField(max_length=20)),
                ('LeaderName', models.CharField(max_length=50)),
                ('WorkStartTime', models.DateTimeField(null=True)),
                ('WorkEndTime', models.DateTimeField(null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createBy', models.CharField(max_length=20, null=True)),
                ('updatetime', models.DateTimeField(null=True)),
                ('updateBy', models.CharField(max_length=20, null=True)),
                ('posttime', models.DateTimeField(null=True)),
                ('postBy', models.CharField(max_length=20, null=True)),
                ('CheckTime', models.DateTimeField(null=True)),
                ('CheckBy', models.CharField(max_length=20, null=True)),
                ('staticcode', models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], default='DRAFT', max_length=20)),
                ('remark', models.TextField(max_length=200)),
            ],
            options={
                'permissions': (('prd_draft_post', '制作初稿到过帐'), ('prd_post_checked', '制作已过帐记录审批'), ('prd_post_draft', '制作已过帐发还到初稿'), ('prd_checked_draft', '制作已批核发还到初稿'), ('prd_delete', '制作初稿删除'), ('prd_post_delete', '制作已过帐删除'), ('prd_checked_delete', '制作已批核删除'), ('prd_delete_draft', '制作已经删除到初稿')),
            },
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 11)),
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkType',
            field=models.CharField(choices=[('SMY', ' 数码样'), ('LZ', '蓝纸'), ('CTP', 'CTP'), ('CTF', 'CTF'), ('GB', '改版'), ('SBL', '算倍率'), ('COPYDOT', 'COPYDOT'), ('KP', '刻盘')], max_length=50),
        ),
    ]
