# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0007_auto_20171211_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_table',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pro_table',
            name='remark',
            field=models.CharField(max_length=200),
        ),
    ]
