# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0009_auto_20171212_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='df_table',
            options={'permissions': (('df_draft_post', '电分初稿到过帐'), ('df_post_checked', '电分已过帐记录审批'), ('df_post_draft', '电分已过帐发还到初稿'), ('df_checked_draft', '电分已批核发还到初稿'), ('df_delete', '电分初稿删除'), ('df_post_delete', '电分已过帐删除'), ('df_checked_delete', '电分已批核删除'), ('df_delete_draft', '电分已经删除到初稿'))},
        ),
        migrations.AlterField(
            model_name='df_table',
            name='remark',
            field=models.CharField(max_length=200),
        ),
    ]
