# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0010_auto_20171212_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZJ_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintNum', models.CharField(max_length=20)),
                ('PrintName', models.CharField(max_length=200)),
                ('SubCode', models.CharField(default='A', max_length=10)),
                ('WorkType', models.CharField(choices=[('JGZ', '激光纸'), ('CSG', '查色稿'), ('CLZ', '查蓝纸'), ('CFL', '查菲林'), ('CB', '查版'), ('KB', '烤版'), ('CSMY', '裁数码样')], max_length=20)),
                ('WorkData', models.DateField(null=True)),
                ('WorkTimeType', models.CharField(choices=[('A', '白班'), ('B', '夜班')], max_length=10)),
                ('FinishQty', models.IntegerField(default=0)),
                ('K_val', models.FloatField(default=0.0)),
                ('LeaderCode', models.CharField(max_length=20)),
                ('LeaderName', models.CharField(max_length=50)),
                ('WorkStartTime', models.DateTimeField(null=True)),
                ('WorkEndTime', models.DateTimeField(null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createBy', models.CharField(max_length=20, null=True)),
                ('updatetime', models.DateTimeField(null=True)),
                ('updateBy', models.CharField(max_length=20, null=True)),
                ('posttime', models.DateTimeField(null=True)),
                ('postBy', models.CharField(max_length=20, null=True)),
                ('CheckTime', models.DateTimeField(null=True)),
                ('CheckBy', models.CharField(max_length=20, null=True)),
                ('staticcode', models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], default='DRAFT', max_length=20)),
                ('remark', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('zj_draft_post', '制作初稿到过帐'), ('zj_post_checked', '制作已过帐记录审批'), ('zj_post_draft', '制作已过帐发还到初稿'), ('zj_checked_draft', '制作已批核发还到初稿'), ('zj_delete', '制作初稿删除'), ('zj_post_delete', '制作已过帐删除'), ('zj_checked_delete', '制作已批核删除'), ('zj_delete_draft', '制作已经删除到初稿')),
            },
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 13)),
        ),
    ]
