# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0011_auto_20171213_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OUT_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine', models.CharField(choices=[(1, '1号机(Lotem800)'), (2, '2号机(Magnus800)'), (3, '3号机(Magnus800)')], max_length=20)),
                ('PrintNum', models.CharField(max_length=20)),
                ('PrintName', models.CharField(max_length=200)),
                ('SubCode', models.CharField(default='A', max_length=10)),
                ('WorkType', models.CharField(choices=[('CTP_PB', 'CTP拼版'), ('CTP_CLZ', 'CTP出蓝纸'), ('PS_PB', 'PS拼版'), ('PS_CLZ', 'PS出蓝纸'), ('CTP_CB', 'CTP出版'), ('CTP_BB', 'CTP补版'), ('CTP_CSB', 'CTP测试版')], max_length=20)),
                ('WorkData', models.DateField(null=True)),
                ('WorkTimeType', models.CharField(choices=[('A', '白班'), ('B', '夜班')], max_length=10)),
                ('PS_Type', models.CharField(choices=[('IM500668', 'CTP华光(1030X800)'), ('IM500536', 'CTP华光(1030X790)'), ('IM501521', 'CTP版富士(1030X800)'), ('IM501520', 'CTP版富士(1030X790)'), ('IM501524', 'CTP版富士(968X584)'), ('IM503335', 'CTP版柯达免冲洗(1030X790)'), ('IM500035', 'CTP版柯达(968X604)'), ('IM500746', 'PS版河南光华(1030X800)'), ('IM500041', 'PS版河南光华(1030X790)'), ('IM500990', 'PS版河南光华(968X604)'), ('IM500989', 'PS版河南光华(968X584)')], max_length=20)),
                ('FinishQty', models.IntegerField(default=0)),
                ('LeaderCode', models.CharField(max_length=20)),
                ('LeaderName', models.CharField(max_length=50)),
                ('WorkStartTime', models.DateTimeField(null=True)),
                ('WorkEndTime', models.DateTimeField(null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createBy', models.CharField(max_length=20, null=True)),
                ('updatetime', models.DateTimeField(null=True)),
                ('updateBy', models.CharField(max_length=20, null=True)),
                ('posttime', models.DateTimeField(null=True)),
                ('postBy', models.CharField(max_length=20, null=True)),
                ('CheckTime', models.DateTimeField(null=True)),
                ('CheckBy', models.CharField(max_length=20, null=True)),
                ('staticcode', models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], default='DRAFT', max_length=20)),
                ('remark', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 14)),
        ),
    ]
