# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0012_auto_20171214_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='out_table',
            options={'permissions': (('out_draft_post', '输出初稿到过帐'), ('out_post_checked', '输出表已过帐记录审批'), ('out_post_draft', '输出表已过帐发还到初稿'), ('out_checked_draft', '输出表已批核发还到初稿'), ('out_delete', '输出表初稿删除'), ('out_post_delete', '输出表已过帐删除'), ('out_checked_delete', '输出表已批核删除'), ('out_delete_draft', '输出表已经删除到初稿'))},
        ),
        migrations.AlterField(
            model_name='out_table',
            name='remark',
            field=models.CharField(max_length=200),
        ),
    ]
