# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 10:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tango_app', '0013_auto_20171214_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Longined_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 18)),
        ),
        migrations.AlterField(
            model_name='out_table',
            name='Machine',
            field=models.CharField(choices=[('1', '1号机(Lotem800)'), ('2', '2号机(Magnus800)'), ('3', '3号机(Magnus800)')], max_length=20),
        ),
    ]
