# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0014_auto_20171218_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longined_user',
            old_name='user_session',
            new_name='UserSession',
        ),
    ]
