# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0016_auto_20171219_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_loged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageType', models.CharField(choices=[('IM500668', 'CTP华光(1030X800)'), ('IM500536', 'CTP华光(1030X790)'), ('IM501521', 'CTP版富士(1030X800)'), ('IM501520', 'CTP版富士(1030X790)'), ('IM501524', 'CTP版富士(968X584)'), ('IM503335', 'CTP版柯达免冲洗(1030X790)'), ('IM500035', 'CTP版柯达(968X604)'), ('IM500746', 'PS版河南光华(1030X800)'), ('IM500041', 'PS版河南光华(1030X790)'), ('IM500990', 'PS版河南光华(968X604)'), ('IM500989', 'PS版河南光华(968X584)')], max_length=20)),
                ('UseType', models.CharField(choices=[('OUT', '领出'), ('USED', '使用')], max_length=20)),
                ('Data', models.DateField(null=True)),
                ('Handler', models.CharField(max_length=20)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(max_length=20)),
                ('StaticCode', models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], max_length=20)),
                ('Remark', models.CharField(max_length=200)),
            ],
        ),
    ]
