# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0017_page_loged'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_loged',
            name='WorkTimeType',
            field=models.CharField(choices=[('A', '白班'), ('B', '夜班')], default='A', max_length=20),
        ),
    ]
