# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0018_page_loged_worktimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_loged',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
    ]
