# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0019_page_loged_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_loged',
            name='DeleteBy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page_loged',
            name='DeleteTime',
            field=models.DateTimeField(null=True),
        ),
    ]
