# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tango_app', '0020_auto_20171219_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='df_table',
            name='FinalQty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gw_pre_table',
            name='FinalQty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='out_table',
            name='FinalQty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pro_table',
            name='FinalQty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zj_table',
            name='FinalQty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gw_pre_table',
            name='WorkData',
            field=models.DateField(default=datetime.date(2017, 12, 25)),
        ),
        migrations.AlterField(
            model_name='page_loged',
            name='StaticCode',
            field=models.CharField(choices=[('DRAFT', '初稿'), ('POST', '已过帐'), ('CHECKED', '已审核'), ('DELETED', '已删除')], default='CHECKED', max_length=20),
        ),
    ]
